### ISSUE TITLE
Quelques détails dans le code à améliorer

### ISSUE THREAD

**Issue by fandolfatto** [HentaiShoujo66/NavalBattle_Rajadurai#1]
Quelques constantes à ajouter (47, 10 par exemple)
Nom des fonctions en anglais (Play) et français (verification) => harmoniser : tout mettre en anglais
PlayerInput ne fait pas que récupérer l'entrée du joueur  => créer une 2ème fonction qui vérifie si bateau touché ou non
Dommage que les coordonnées soient en dur pour vérifier si le bateau est coulé
Nom des fonctions et des variables sont parfois avec _ et parfois sans => constance dans le nommage

**Comment by HentaiShoujo66** [comment]
La nomenclature, ainsi que les fonctions sont toutes mises à jour.
