### ISSUE TITLE
La fonction Verification pourrait être améliorée

### ISSUE THREAD

**Issue by fandolfatto** [HentaiShoujo66/NavalBattle_Rajadurai#4]
Ce code
int boat1_sunkparts = 0;                     //reset the sunkparts parts before boat1's check
    for (line = 0; line < GRIDHEIGHT; line++) {                         //counts sunk parts to check if boat1 is sunk
        for (column = 0; column < GRIDLENGTH; ++column) {
            if(playerGrid[line][column] == '1') {
                boat1_sunkparts = boat1_sunkparts + 1;
            }
        }
    }
    if (boat1_sunkparts == 5) {
        if (boat1Msg == false)                       //a condition, so it only displays sunk one time
        {
            Boom();
            printf("Porte-avions coulé!\n");
            fprintf(logPointer," \nTour %d : Le joueur a coulé le Porte-avions",score);
            boat1Msg = true;
        }
        sunkBoats = sunkBoats + 1;
    }
se répète beaucoup dans la fonction Verification().... à voir comment éviter ces répétitions avec l'utilisation d'une fonction (avec paramètres et retour de fonctions).

**Comment by fandolfatto** [comment]
Détail : La fonction Verification() devrait être nommée en anglais

**Comment by fandolfatto** [comment]
Il y a quelques autres fonctions en français à renommer en anglais...

**Comment by HentaiShoujo66** [comment]
> Détail : La fonction Verification() devrait être nommée en anglais

"Verification" est un mot anglais. "Vérification" est un mot français

**Comment by HentaiShoujo66** [comment]
> Il y a quelques autres fonctions en français à renommer en anglais...

TOUT est en anglais ( à part une seule fonction : Bateau).
