### ISSUE TITLE
Gestion du score

### ISSUE THREAD

**Issue by fandolfatto** [HentaiShoujo66/NavalBattle_Rajadurai#5]
La gestion du score me semble bizarre : que le bateau soit touché ou raté, le score est incrémenté de 1....

**Comment by HentaiShoujo66** [comment]
C'est normal, le système de score est expliqué explicitement dans le menu aide du jeu.
Chaque tour, le score est augmenté de 1. Plus le score est bas, meilleur est la performance du joueur, tout comme au golf.

**Comment by fandolfatto** [comment]
Désolée, je ne joue pas au golf.....
Je trouve un peu dommage que le score se limite au nombre de tours de jeu (mais vous étiez libre d'y mettre ce que vous vouliez, donc pourquoi pas?). Je trouve que, dans la bataille navale, il est bien de récompenser les tirs gagnés ou les bateaux coulés mais ça n'engage que moi!
